{{- if .Values.ingress.enabled }}
---
# Lake UI
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "lake-of-tears.fullname" . }}-lakeui
  labels:
    {{- include "lake-of-tears.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hosts.lakeui }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "lake-of-tears.fullname" . }}-lakeui
                port:
                  name: http

---
# Jupyter Lab
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "lake-of-tears.fullname" . }}-jupyter
  labels:
    {{- include "lake-of-tears.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hosts.jupyter }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "lake-of-tears.fullname" . }}-jupyter
                port:
                  name: http

---
# Apache Superset
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "lake-of-tears.fullname" . }}-superset
  labels:
    {{- include "lake-of-tears.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hosts.superset }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "lake-of-tears.fullname" . }}-superset
                port:
                  name: http

---
# Apache Airflow
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "lake-of-tears.fullname" . }}-airflow
  labels:
    {{- include "lake-of-tears.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hosts.airflow }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "lake-of-tears.fullname" . }}-airflow
                port:
                  name: http

---
# MinIO Console
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "lake-of-tears.fullname" . }}-minio
  labels:
    {{- include "lake-of-tears.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hosts.minio }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  name: console
{{- end }}
